llm:
  provider: "ollama"  # or "lmstudio"
  endpoint: "http://localhost:11434"  # For Ollama; adjust for LMStudio
  models:
    - name: "gemma3:4b"
      type: "vision"  # Gemma 3 4B is multimodal - supports both text and images
      description: "Gemma 3 4B multimodal model (supports text and images)"
    - name: "gemma3:4b"
      type: "text"  # Vision model - needs to be installed
      description: "Multimodal LLM for direct image processing"
  default_model: "gemma3:4b"
  parameters:
    temperature: 0.1      # Controls randomness (0.0-2.0, lower = more focused)
    top_p: 0.9           # Nucleus sampling (0.0-1.0, controls diversity)
    top_k: 40            # Top-k sampling (limits token choices)
    num_ctx: 128000        # Context window size (max tokens for input)
    num_predict: 128000    # Maximum output tokens

ocr:
  engine: "tesseract"  # Only supported for now; could extend to others
  languages: ["eng", "fra", "deu", "spa", "ita", "por", "chi_sim", "jpn", "kor"]  # Tesseract language codes
  default_language: "eng"
  path: "/usr/local/bin/tesseract"  # Optional path to Tesseract binary

preprocessing:
  enabled_by_default: true  # Changed to true for automatic preprocessing
  auto_detect: true  # Enable automatic quality detection
  quality_thresholds:
    blur_threshold: 100  # Below this value, image is considered blurry
    contrast_threshold: 40  # Below this value, image has low contrast
    brightness_min: 80  # Below this value, image is too dark
    brightness_max: 200  # Above this value, image is too bright
    noise_threshold: 15  # Above this value, image is noisy
    confidence_threshold: 60  # Below this OCR confidence, apply thresholding
  steps:
    - grayscale
    - skew_correction
    - brightness_adjustment
    - contrast_enhancement
    - denoising
    - sharpening
    - adaptive_threshold

general:
  max_images: 50  # Limit for folder processing to avoid overload
  temp_dir: "./temp"  # For storing processed files
  supported_formats:
    - jpg
    - jpeg
    - png
    - bmp
    - tiff
    - tif
    - pdf
  parallel_processing: false  # Enable/disable parallel processing
  batch_size: 10  # Default batch size for large sets